[build-system]
requires = ["hatchling>=1.18"]
build-backend = "hatchling.build"

[project]
name = "signxai2"
version = "0.0.0"  # will be auto-updated by python-semantic-release
authors = [
    {name = "TimeXAIgroup", email = "jennifer.hannig@kite.thm.de"},
]
maintainers = [
    {name = "Nils Gumpfer", email = "nils.gumpfer@kite.thm.de"},
]
description = "Extended variant of ZeNNit with SIGNed explanations - Unveiling relevant features by reducing bias"
readme = "README.md"
license = "GPL-3.0"
requires-python = ">=3.11.11"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Image Classification",
    "Topic :: Scientific/Engineering :: Time Series Classification",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent"
]
keywords = ["explainable ai", "xai", "interpretability", "machine learning", "deep learning", "pytorch", "lrp", "layer-wise relevance propagation", "grad-cam", "sign", "attribution", "saliency"]
dependencies = [
    "zennit==1.0.0"
]

[project.urls]
Homepage = "https://www.thm.de/mnd/jennifer-hannig/timexai-erklaerbare-kuenstliche-intelligenz-fuer-zeitreihen"
Documentation = "https://TimeXAIgroup.github.io/signxai2/index.html"
Repository = "https://github.com/TimeXAIgroup/signxai2.git"
"Bug Reports" = "https://github.com/TimeXAIgroup/signxai2/issues"
Changelog = "https://github.com/TimeXAIgroup/signxai2/blob/main/CHANGELOG.md"
"Publication" = "https://www.sciencedirect.com/science/article/pii/S1566253523001999?via%3Dihub"

[tool.semantic_release]
branch = "main"  # release only from main
version_toml = ["pyproject.toml:project.version"]
build_command = "python -m build"
upload_to_pypi = false
changelog_file = "CHANGELOG.md"